#!/bin/bash

python -c """
import taxi
import taxi.tools as tools
import taxi.mcmc

command_line_args = '$*'.split()
d = tools.load.dispatch(command_line_args[0])

tasks = d.get_all_tasks(include_complete=True)
rollback_task = tasks[int(command_line_args[1])]

d.rollback(rollback_task, rollback_dir='./rollback/')
"""


